name: hesn_elmuslim
description: All muslim needs in one app.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.4

environment:
  sdk: ">=3.1.0 <4.0.0"


dependencies:

  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  conditional_builder_null_safety: ^0.0.6
  percent_indicator: ^4.2.3
  flutter_screenutil: ^5.8.4
  lottie: ^2.6.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  share_plus: ^7.1.0
  flutter_qiblah: ^2.2.0
  adhan: ^2.0.0-nullsafety.2
  intl: ^0.18.1
  geolocator: ^10.0.0
  dio: ^5.3.2
  hijri: ^3.0.0
  arabic_numbers: ^1.0.0
  analog_clock: ^0.1.1
  device_info_plus: ^9.0.3
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.2.0
  vibration: ^1.8.1
  awesome_dialog: ^3.1.0
  store_redirect: ^2.0.1
  pdfx: ^2.4.0
  dartz: ^0.10.1
  get_it: ^7.6.0
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  animate_do: ^3.0.2
  rename: ^2.1.1

  audioplayers: ^5.1.0
  audio_video_progress_bar: ^1.0.1
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  rxdart: ^0.27.7
  image_picker: ^1.0.2
  awesome_notifications: ^0.7.4+1
  path_provider: ^2.1.0
  http: ^1.1.0
  onesignal_flutter: ^3.5.1
  url_launcher: ^6.1.12
  upgrader: ^8.1.0
  flutter_share: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  background_color: "#FFFFFF"

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#F3F7FA"
  image: "assets/images/logo.png"
  android: true
  iso: true

  android_12:
    image: "assets/images/logo12Splash.png"
    icon_background_color: "#F3F7FA"

  web: false

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/images/
    - assets/json/
    - assets/icons/
    - assets/pdf/
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

